# Generated by Django 4.0 on 2021-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('chant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('all_lesson_material', models.ManyToManyField(related_name='all', to='app.Symbol')),
                ('main_lesson_material', models.ManyToManyField(related_name='main', to='app.Symbol')),
            ],
        ),
    ]
